name: Parse Twitch Clip

on:
  workflow_dispatch:
    inputs:
      clip_url:
        description: 'Twitch Clip URL'
        required: true
        type: string
      mode:
        description: 'Processing Mode (e.g. opr1920, zoo1920)'
        required: true
        type: string

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Project Workspace
        uses: ./.github/actions/setup-project
        with:
          mode: ${{ inputs.mode }}

      - name: Create Credentials File
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Convert twitch clip to google sheets
        run: pnpm start "${{ inputs.clip_url }}" --mode "${{ inputs.mode }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

      - name: Upload Scoreboard Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: scoreboard-pipeline-results
          path: |
            .tmp/scoreboard.csv
            .tmp/stitched.png
          include-hidden-files: true

      - name: Take screenshots
        run: pnpm start screenshot --mode "${{ inputs.mode }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json

      - name: Upload Screenshot Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: spreadsheet-screenshots
          path: |
            .tmp/spreadsheet*.png
          include-hidden-files: true
